LampShade/ServiceHost/Areas/Administration/Pages/Blog/ArticleCategories/Index.cshtml.cs
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.ArticleCategory;
using BlogManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Blog.ArticleCategories
{
    public class IndexModel : PageModel
    {
        public ArticleCategorySearchModel SearchModel;
        public List<ArticleCategoryViewModel> ArticleCategories;

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        [NeedsPermission(BlogPermissions.ListArticleCategories)]
        public void OnGet(ArticleCategorySearchModel searchModel)
        {
            ArticleCategories = _articleCategoryApplication.Search(searchModel);
        }

        [NeedsPermission(BlogPermissions.CreateArticleCategory)]
        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateArticleCategory());
        }

        [NeedsPermission(BlogPermissions.CreateArticleCategory)]
        public JsonResult OnPostCreate(CreateArticleCategory RegisterModel)
        {

            var result = _articleCategoryApplication.Create(RegisterModel);
            return new JsonResult(result);
        }

        [NeedsPermission(BlogPermissions.EditArticleCategory)]
        public IActionResult OnGetEdit(long id)
        {
            var productCategory = _articleCategoryApplication.GetDetails(id);
            return Partial("Edit", productCategory);
        }

        [NeedsPermission(BlogPermissions.EditArticleCategory)]
        public JsonResult OnPostEdit(EditArticleCategory RegisterModel)
        {
            var result = _articleCategoryApplication.Edit(RegisterModel);
            return new JsonResult(result);
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using BlogManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        public CreateArticle RegisterModel;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        [NeedsPermission(BlogPermissions.CreateArticle)]
        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        [NeedsPermission(BlogPermissions.CreateArticle)]
        public IActionResult OnPost(CreateArticle RegisterModel)
        {
            if (!ModelState.IsValid) { 
                ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
            return Page();
                }
            var result = _articleApplication.Create(RegisterModel);
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using BlogManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        public EditArticle RegisterModel;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        [NeedsPermission(BlogPermissions.EditArticle)]
        public void OnGet(long id)
        {
            RegisterModel = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        [NeedsPermission(BlogPermissions.EditArticle)]
        public IActionResult OnPost(EditArticle RegisterModel)
        {
            var result = _articleApplication.Edit(RegisterModel);
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Index.cshtml.cs
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using BlogManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class IndexModel : PageModel
    {
        public ArticleSearchModel SearchModel;
        public List<ArticleViewModel> Articles;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        [NeedsPermission(BlogPermissions.ListArticles)]
        public void OnGet(ArticleSearchModel searchModel)
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
            Articles = _articleApplication.Search(searchModel);
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/ProductCategories/Index.cshtml.cs
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Configuration.Permissions;
using System.Collections.Generic;
using System.Linq;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        public ProductCategorySearchModel SearchModel;
        public List<ProductCategoryViewModel> ProductCategories;

        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }

        [NeedsPermission(ShopPermissions.ListProductCategories)]
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public JsonResult OnPostCreate(CreateProductCategory RegisterModel)
        {
            var result = _productCategoryApplication.Create(RegisterModel);
            return new JsonResult(result);
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public IActionResult OnGetEdit(long id)
        {
            var productCategory = _productCategoryApplication.GetDetails(id);
            return Partial("Edit", productCategory);
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public JsonResult OnPostEdit(EditProductCategory RegisterModel)
        {
            var result = _productCategoryApplication.Edit(RegisterModel);
            return new JsonResult(result);
        }

    }
}

LampShade/ServiceHost/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LampShade/ServiceHost/Pages/ArticleCategory.cshtml.cs
using _01_LampshadeQuery.Contracts.Article;
using _01_LampshadeQuery.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Pages
{
    public class ArticleCategoryModel : PageModel
    {
        public ArticleCategoryQueryModel ArticleCategory;
        public List<ArticleCategoryQueryModel> ArticleCategories;
        public List<ArticleQueryModel> LatestArticles;

        private readonly IArticleQuery _articleQuery;
        private readonly IArticleCategoryQuery _articleCategoryQuery;

        public ArticleCategoryModel(IArticleCategoryQuery articleCategoryQuery, IArticleQuery articleQuery)
        {
            _articleQuery = articleQuery;
            _articleCategoryQuery = articleCategoryQuery;
        }

        public void OnGet(string id)
        {
            LatestArticles = _articleQuery.LatestArticles();
            ArticleCategory = _articleCategoryQuery.GetArticleCategory(id);
            ArticleCategories = _articleCategoryQuery.GetArticleCategories();
        }
    }
}

LampShade/ServiceHost/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nancy.Json;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Pages
{
    public class CartModel : PageModel
    {
        [TempData]
        public string CartMessage { get; set; }
        public List<CartItem> CartItems;
        public const string CookieName = "cart-items";
        private readonly IProductQuery _productQuery;

        public CartModel(IProductQuery productQuery)
        {
            CartItems = new List<CartItem>();
            _productQuery = productQuery;
        }

        public void OnGet()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];

            var cartItems = string.IsNullOrWhiteSpace(value)
                ? new List<CartItem>()
                : serializer.Deserialize<List<CartItem>>(value);

            cartItems = NormalizeCartItems(cartItems);

            if (!cartItems.Any())
                CartMessage = "سبد خرید شما خالی است.";
            else
                CartItems = _productQuery.CheckInventoryStatus(cartItems);
        }

        public IActionResult OnGetRemoveFromCart(long id)
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];
            Response.Cookies.Delete(CookieName);
            var cartItems = serializer.Deserialize<List<CartItem>>(value);
            var itemToRemove = cartItems.FirstOrDefault(x => x.Id == id);
            cartItems.Remove(itemToRemove);
            var options = new CookieOptions {IsEssential=true, Expires = DateTime.Now.AddDays(2) };
            Response.Cookies.Append(CookieName, serializer.Serialize(cartItems), options);
            return RedirectToPage("/Cart");
        }

        public IActionResult OnGetGoToCheckOut()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];

            var cartItems = string.IsNullOrWhiteSpace(value)
                ? new List<CartItem>()
                : serializer.Deserialize<List<CartItem>>(value);

            cartItems = NormalizeCartItems(cartItems);

            if (!cartItems.Any())
                return RedirectToPage("/Cart");

            CartItems = _productQuery.CheckInventoryStatus(cartItems);

            return RedirectToPage(CartItems.Any(x => !x.IsInStock) ? "/Cart" : "/Checkout");
        }

        private List<CartItem> NormalizeCartItems(List<CartItem> items)
        {
            foreach (var item in items)
            {
                if (item.Count < 1)
                    item.Count = 1;

                item.CalculateTotalItemPrice();
            }
            return items;
        }
    }
}

LampShade/ServiceHost/Pages/Checkout.cshtml.cs
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using _0_Framework.Application;
using _0_Framework.Application.ZarinPal;
using _01_LampshadeQuery.Contracts;
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nancy.Json;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Pages
{
    [Authorize]
    public class CheckoutModel : PageModel
    {
        public Cart Cart;
        public const string CookieName = "cart-items";
        private readonly IAuthHelper _authHelper;
        private readonly ICartService _cartService;
        private readonly IProductQuery _productQuery;
        private readonly IZarinPalFactory _zarinPalFactory;
        private readonly IOrderApplication _orderApplication;
        private readonly ICartCalculatorService _cartCalculatorService;

        public CheckoutModel(ICartCalculatorService cartCalculatorService, ICartService cartService,
            IProductQuery productQuery, IOrderApplication orderApplication, IZarinPalFactory zarinPalFactory,
            IAuthHelper authHelper)
        {
            Cart = new Cart();
            _cartCalculatorService = cartCalculatorService;
            _cartService = cartService;
            _productQuery = productQuery;
            _orderApplication = orderApplication;
            _zarinPalFactory = zarinPalFactory;
            _authHelper = authHelper;
        }

        public IActionResult OnGet()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];

            var cartItems = string.IsNullOrWhiteSpace(value)
                ? new List<CartItem>()
                : serializer.Deserialize<List<CartItem>>(value);

            if (!cartItems.Any())
                return RedirectToPage("/Cart");

            foreach (var item in cartItems)
            {
                if (item.Count < 1)
                    item.Count = 1;
                item.CalculateTotalItemPrice();
            }

            Cart = _cartCalculatorService.ComputeCart(cartItems);
            _cartService.Set(Cart);

            return Page();
        }

        public IActionResult OnPostPay(int paymentMethod)
        {
            var cart = _cartService.Get();

            cart.SetPaymentMethod(paymentMethod);

            var result = _productQuery.CheckInventoryStatus(cart.Items);
            if (result.Any(x => !x.IsInStock))
                return RedirectToPage("/Cart");

            var orderId = _orderApplication.PlaceOrder(cart);
            if (paymentMethod == 1)
            {
                var paymentResponse = _zarinPalFactory.CreatePaymentRequest(
                    cart.PayAmount.ToString(CultureInfo.InvariantCulture), "", "",
                    "خرید از درگاه لوازم خانگی و دکوری", orderId);

                return Redirect(
                    $"https://{_zarinPalFactory.Prefix}.zarinpal.com/pg/StartPay/{paymentResponse.Authority}");
            }

            var paymentResult = new PaymentResult();

            Response.Cookies.Delete("cart-items");

            return RedirectToPage("/PaymentResult",
                paymentResult.Succeeded(
                    "سفارش شما با موفقیت ثبت شد. پس از تماس کارشناسان ما و پرداخت وجه، سفارش ارسال خواهد شد.", null));
        }

        public IActionResult OnGetCallBack([FromQuery] string authority, [FromQuery] string status,
            [FromQuery] long oId)
        {
            var orderAmount = _orderApplication.GetAmountBy(oId);
            var verificationResponse =
                _zarinPalFactory.CreateVerificationRequest(authority,
                    orderAmount.ToString(CultureInfo.InvariantCulture));

            var result = new PaymentResult();
            if (status == "OK" && verificationResponse.Status >= 100)
            {
                var issueTrackingNo = _orderApplication.PaymentSucceeded(oId, verificationResponse.RefID);
                Response.Cookies.Delete("cart-items");
                result = result.Succeeded("پرداخت با موفقیت انجام شد.", issueTrackingNo);
                return RedirectToPage("/PaymentResult", result);
            }

            result = result.Failed(
                "پرداخت با موفقیت انجام نشد. درصورت کسر وجه از حساب، مبلغ تا 24 ساعت دیگر به حساب شما بازگردانده خواهد شد.");
            return RedirectToPage("/PaymentResult", result);
        }
    }
}

LampShade/ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <title>دسترسی غیرمجاز</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/admintheme/access-denied.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="icon"></div>
        <h1>۴۰۴ - دسترسی غیرمجاز</h1>
        <p>.متأسفیم! شما اجازه دسترسی به این مسیر را ندارید</p>
        <a href="/">بازگشت به صفحه اصلی</a>
    </div>
</body>
</html>

LampShade/ServiceHost/Pages/Cart.cshtml
@page
@using _0_Framework.Application
@model ServiceHost.Pages.CartModel
@{
    ViewData["Title"] = "سبد خرید";
}

<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">سبد خرید شما</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li>
                                <a asp-page="./Index">صفحه اصلی</a>
                            </li>
                            <li class="active">سبد خرید</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">

                    @if (!string.IsNullOrWhiteSpace(Model.CartMessage))
                    {
                        <div class="alert alert-warning">
                            @Model.CartMessage
                        </div>
                    }

                    <div id="productStockWarnings">
                        @foreach (var item in Model.CartItems.Where(x => !x.IsInStock))
                        {
                            <div class="alert alert-warning" id="@item.Id">
                                <i class="fa fa-warning"></i> کالای
                                <strong>@item.Name</strong>
                                در انبار کمتر از تعداد درخواستی موجود است.
                            </div>
                        }
                    </div>

                    <div class="page-content-wrapper">
                        <div class="cart-table table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="pro-thumbnail">عکس</th>
                                        <th class="pro-title">محصول</th>
                                        <th class="pro-price">قیمت واحد</th>
                                        <th class="pro-quantity">تعداد</th>
                                        <th class="pro-subtotal">قیمت کل</th>
                                        <th class="pro-remove">حذف</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.CartItems)
                                    {
                                        <tr>
                                            <td class="pro-thumbnail">
                                                <a href="single-product.html">
                                                    <img src="~/images/@item.Picture" class="img-fluid" alt="@item.Name">
                                                </a>
                                            </td>
                                            <td class="pro-title">
                                                <a href="single-product.html">@item.Name</a>
                                            </td>
                                            <td class="pro-price">
                                                <span>@item.UnitPrice.ToMoney()</span>
                                            </td>
                                            <td class="pro-quantity">
                                                <div class="quantity-selection">
                                                    <input type="number"
                                                           class="cart-quantity"
                                                           data-id="@item.Id"
                                                           data-total-id="totalItemPrice-@item.Id"
                                                           value="@item.Count" min="1"
                                                           onchange="changeCartItemCount('@item.Id', 'totalItemPrice-@item.Id', this.value)">
                                                </div>
                                            </td>
                                            <td class="pro-subtotal">
                                                <span id="totalItemPrice-@item.Id">@item.TotalItemPrice.ToMoney()</span>
                                            </td>
                                            <td class="pro-remove">
                                                <a asp-page-handler="RemoveFromCart" asp-route-id="@item.Id">
                                                    <i class="fa fa-trash-o"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-12 d-flex">
                                <div class="cart-summary">
                                     @if (Model.CartItems.Any())
                                    {
                                    <div class="cart-summary-button">
                                        <a class="checkout-btn" asp-page-handler="GoToCheckOut">تکمیل فرایند خرید</a>
                                    </div>
                                     }
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LampShade/ServiceHost/Pages/Checkout.cshtml
@page
@using _0_Framework.Application
@using ShopManagement.Application.Contracts
@model ServiceHost.Pages.CheckoutModel
@{
    ViewData["Title"] = "تایید سبد خرید و پرداخت";
}

<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">تایید سبد خرید / پرداخت</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li>
                                <a asp-page="./Index">صفحه اصلی</a>
                            </li>
                            <li class="active">تایید سبد خرید / پرداخت</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <form method="post">
                            <div class="cart-table table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th class="pro-thumbnail">عکس</th>
                                            <th class="pro-thumbnail">محصول</th>
                                            <th class="pro-title">قیمت واحد</th>
                                            <th class="pro-price">تعداد</th>
                                            <th class="pro-quantity">مبلغ کل بدون تخفیف</th>
                                            <th class="pro-subtotal">درصد تخفیف</th>
                                            <th class="pro-subtotal">مبلغ کل تخفیف</th>
                                            <th class="pro-remove">مبلغ پس از تخفیف</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Cart.Items)
                                        {
                                            <tr>
                                                <td class="pro-thumbnail">
                                                    <a>
                                                        <img src="~/images/@item.Picture" class="img-fluid"
                                                             alt="@item.Name">
                                                    </a>
                                                </td>
                                                <td class="pro-title">
                                                    <a>@item.Name</a>
                                                </td>
                                                <td class="pro-price">
                                                    <span>@item.UnitPrice.ToMoney() تومان</span>
                                                </td>
                                                <td class="pro-price">
                                                    <span>@item.Count عدد</span>
                                                </td>
                                                <td class="pro-subtotal">
                                                    <span>@item.TotalItemPrice.ToMoney() تومان</span>
                                                </td>
                                                <td class="pro-subtotal">
                                                    <span>@item.DiscountRate %</span>
                                                </td>
                                                <td class="pro-subtotal">
                                                    <span>@item.DiscountAmount.ToMoney() تومان</span>
                                                </td>
                                                <td class="pro-subtotal">
                                                    <span>@item.ItemPayAmount.ToMoney() تومان</span>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                            <div class="row">
                                <div class="col-lg-6 col-12 d-flex">
                                    <div class="checkout-payment-method">
                                        <h4>نحوه پرداخت</h4>
                                        @foreach (var method in PaymentMethod.GetList())
                                        {
                                            <div class="single-method">
                                                <input type="radio" id="payment_@method.Id" name="paymentMethod" value="@method.Id" @(PaymentMethod.GetList().First().Id == method.Id ? "checked" : "")>
                                                <label for="payment_@method.Id">@method.Name</label>
                                                <p data-method="@method.Id" style="display:@(PaymentMethod.GetList().First().Id == method.Id ? "block" : "none")">@method.Description</p>
                                            </div>
                                        }
                                    </div>
                                </div>
                                <div class="col-lg-6 col-12 d-flex">
                                    <div class="cart-summary">
                                        <div class="cart-summary-wrap">
                                            <h4>خلاصه وضعیت فاکتور</h4>
                                            <p>مبلغ نهایی <span>@Model.Cart.TotalAmount.ToMoney() تومان</span></p>
                                            <p>مبلغ تخفیف <span>@Model.Cart.DiscountAmount.ToMoney() تومان</span></p>
                                            <h2>مبلغ قابل پرداخت <span>@Model.Cart.PayAmount.ToMoney() تومان</span></h2>
                                        </div>
                                        <div class="cart-summary-button">
                                            <button asp-page-handler="Pay" class="checkout-btn">پرداخت</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LampShade/ServiceHost/Pages/Logout.cshtml
@page
@model ServiceHost.Pages.LogoutModel
@{
}