LampShade/ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using AccountManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public CreateRole RegisterModel { get; set; }

        [TempData]
        public string Message { get; set; }

        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        [NeedsPermission(AccountPermissions.CreateRole)]
        public void OnGet()
        {
        }

        [NeedsPermission(AccountPermissions.CreateRole)]

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
                return Page();

            var result = _roleApplication.Create(RegisterModel);
            if (result.IsSucceded)
                return RedirectToPage("Index");

            ModelState.AddModelError("RegisterModel.Name", result.Message);
            return Page();
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using AccountManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public EditRole RegisterModel;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        [NeedsPermission(AccountPermissions.EditRole)]
        public void OnGet(long id)
        {
            RegisterModel = _roleApplication.GetDetails(id);

            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    var group = new SelectListGroup { Name = key };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (RegisterModel.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);
                    }
                }
            }
        }

        [NeedsPermission(AccountPermissions.EditRole)]
        public IActionResult OnPost(EditRole RegisterModel)
        {
            var result = _roleApplication.Edit(RegisterModel);
            return RedirectToPage("Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using BlogManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        public CreateArticle RegisterModel;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        [NeedsPermission(BlogPermissions.CreateArticle)]
        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        [NeedsPermission(BlogPermissions.CreateArticle)]
        public IActionResult OnPost(CreateArticle RegisterModel)
        {
            if (!ModelState.IsValid) { 
                ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
            return Page();
                }
            var result = _articleApplication.Create(RegisterModel);
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using BlogManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        public EditArticle RegisterModel;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        [NeedsPermission(BlogPermissions.EditArticle)]
        public void OnGet(long id)
        {
            RegisterModel = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        [NeedsPermission(BlogPermissions.EditArticle)]
        public IActionResult OnPost(EditArticle RegisterModel)
        {
            var result = _articleApplication.Edit(RegisterModel);
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Discounts/ColleagueDiscounts/Index.cshtml.cs
using _0_Framework.Infrastructure;
using DiscountManagement.Application.Contracts.ColleagueDiscount;
using DiscountManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Discounts.ColleagueDiscounts
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public ColleagueDiscountSearchModel SearchModel;
        public List<ColleagueDiscountViewModel> ColleagueDiscounts;
        public SelectList Products;

        private readonly IProductApplication _productApplication;
        private readonly IColleagueDiscountApplication _colleagueDiscountApplication;

        public IndexModel(IProductApplication ProductApplication, IColleagueDiscountApplication colleagueDiscountApplication)
        {
            _productApplication = ProductApplication;
            _colleagueDiscountApplication = colleagueDiscountApplication;
        }

        [NeedsPermission(DiscountPermissions.ListColleagueDiscounts)]
        public void OnGet(ColleagueDiscountSearchModel searchModel)
        {
            Products = new SelectList(_productApplication.GetProducts(), "Id", "Name");
            ColleagueDiscounts = _colleagueDiscountApplication.Search(searchModel);
        }

        [NeedsPermission(DiscountPermissions.CreateColleagueDiscount)]
        public IActionResult OnGetCreate()
        {
            var RegisterModel = new DefineColleagueDiscount
            {
                Products = _productApplication.GetProducts()
            };
            return Partial("./Create", RegisterModel);
        }

        [NeedsPermission(DiscountPermissions.CreateColleagueDiscount)]
        public JsonResult OnPostCreate(DefineColleagueDiscount RegisterModel)
        {
            var result = _colleagueDiscountApplication.Define(RegisterModel);
            return new JsonResult(result);
        }

        [NeedsPermission(DiscountPermissions.EditColleagueDiscount)]
        public IActionResult OnGetEdit(long id)
        {
            var colleagueDiscount = _colleagueDiscountApplication.GetDetails(id);
            colleagueDiscount.Products = _productApplication.GetProducts();
            return Partial("Edit", colleagueDiscount);
        }

        [NeedsPermission(DiscountPermissions.EditColleagueDiscount)]
        public JsonResult OnPostEdit(EditColleagueDiscount RegisterModel)
        {
            var result = _colleagueDiscountApplication.Edit(RegisterModel);
            return new JsonResult(result);
        }

        [NeedsPermission(DiscountPermissions.RemoveColleagueDiscount)]
        public IActionResult OnGetRemove(long id)
        {
            _colleagueDiscountApplication.Remove(id);
            return RedirectToPage("./Index");
        }

        [NeedsPermission(DiscountPermissions.RestoreColleagueDiscount)]
        public IActionResult OnGetRestore(long id)
        {
            _colleagueDiscountApplication.Restore(id);
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Discounts/CustomerDiscounts/Index.cshtml.cs
using _0_Framework.Infrastructure;
using DiscountManagement.Application.Contracts.CustomerDiscount;
using DiscountManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Discounts.CustomerDiscounts
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public CustomerDiscountSearchModel SearchModel;
        public List<CustomerDiscountViewModel> CustomerDiscounts;
        public SelectList Products;

        private readonly IProductApplication _productApplication;
        private readonly ICustomerDiscountApplication _customerDiscountApplication;

        public IndexModel(IProductApplication ProductApplication, ICustomerDiscountApplication customerDiscountApplication)
        {
            _productApplication = ProductApplication;
            _customerDiscountApplication = customerDiscountApplication;
        }

        [NeedsPermission(DiscountPermissions.ListCustomerDiscounts)]
        public void OnGet(CustomerDiscountSearchModel searchModel)
        {
            Products = new SelectList(_productApplication.GetProducts(), "Id", "Name");
            CustomerDiscounts = _customerDiscountApplication.Search(searchModel);
        }

        [NeedsPermission(DiscountPermissions.CreateCustomerDiscount)]
        public IActionResult OnGetCreate()
        {
            var RegisterModel = new DefineCustomerDiscount
            {
                Products = _productApplication.GetProducts()
            };
            return Partial("./Create", RegisterModel);
        }

        [NeedsPermission(DiscountPermissions.CreateCustomerDiscount)]
        public JsonResult OnPostCreate(DefineCustomerDiscount RegisterModel)
        {
            var result = _customerDiscountApplication.Define(RegisterModel);
            return new JsonResult(result);
        }

        [NeedsPermission(DiscountPermissions.EditCustomerDiscount)]
        public IActionResult OnGetEdit(long id)
        {
            var customerDiscount = _customerDiscountApplication.GetDetails(id);

            customerDiscount.Products = _productApplication.GetProducts();
            return Partial("Edit", customerDiscount);
        }

        [NeedsPermission(DiscountPermissions.EditCustomerDiscount)]
        public JsonResult OnPostEdit(EditCustoemrDiscount RegisterModel)
        {
            var result = _customerDiscountApplication.Edit(RegisterModel);
            return new JsonResult(result);
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Discounts/ColleagueDiscounts/Create.cshtml
@using DiscountManagement.Application.Contracts.ColleagueDiscount
@model DefineColleagueDiscount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">تعریف تخفیف همکاری جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">انتخاب محصول</label>
                    <select class="form-control" asp-for="ProductId"
                            asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="0">انتخاب محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DiscountRate" class="control-label">درصد تخفیف</label>
                    <input type="text" class="form-control" asp-for="DiscountRate">
                    <span asp-validation-for="DiscountRate" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">تعریف</button>
    </div>
</form>

LampShade/ServiceHost/Areas/Administration/Pages/Discounts/ColleagueDiscounts/Edit.cshtml
@using DiscountManagement.Application.Contracts.ColleagueDiscount
@model EditColleagueDiscount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش تخفیف همکاری</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">انتخاب محصول</label>
                    <select class="form-control" asp-for="ProductId"
                            asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="0">انتخاب محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DiscountRate" class="control-label">درصد تخفیف</label>
                    <input type="text" class="form-control" asp-for="DiscountRate">
                    <span asp-validation-for="DiscountRate" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

LampShade/ServiceHost/Areas/Administration/Pages/Discounts/ColleagueDiscounts/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Discounts.ColleagueDiscounts.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت تخفیفات همکاران";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">تعریف تخفیف همکاری</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در تخفیفات همکاران</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items="Model.Products">
                            <option value="0">انتخاب محصول ...</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست تخفیفات همکاران (@Html.FaNumbersPlainText(@Model.ColleagueDiscounts.Count))</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>محصول</th>
                                    <th>درصد تخفیف</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ColleagueDiscounts)
                                {
                                    <tr>
                                        <td>@Html.FaNumbersPlainText(@item.Id)</td>
                                        <td>@Html.FaNumbersPlainText(@item.Product)</td>
                                        <td>@Html.FaNumbersPlainText(@item.DiscountRate+"%")</td>
                                        <td>@Html.FaPersianDate(@item.CreationDate)</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            @if (item.IsRemoved)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Restore" asp-route-id="@item.Id"
                                                   class="btn btn-success waves-effect waves-light m-b-5">فعال سازی</a>
                                            }
                                            else
                                            {
                                                <a asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id"
                                                   class="btn btn-danger waves-effect waves-light m-b-5">غیرفعال</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}