LampShade/ServiceHost/Areas/Administration/Pages/Comments/Index.cshtml.cs
using _0_Framework.Infrastructure;
using CommentManagement.Application.Contracts.Comment;
using CommentManagement.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Comments
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<CommentViewModel> Comments;
        public CommentSearchModel SearchModel;
        private readonly ICommentApplication _commentApplication;

        public IndexModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        [NeedsPermission(CommentPermissions.ListComments)]
        public void OnGet(CommentSearchModel searchModel)
        {
            Comments = _commentApplication.Search(searchModel);
        }

        [NeedsPermission(CommentPermissions.CancelComment)]
        public IActionResult OnGetCancel(long id)
        {
            var result = _commentApplication.Cancel(id);
            if (result.IsSucceded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }

        [NeedsPermission(CommentPermissions.ConfirmComment)]
        public IActionResult OnGetConfirm(long id)
        {
            var result = _commentApplication.Confirm(id);
            if (result.IsSucceded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Comments/Index.cshtml
@page
@model Areas.Administration.Pages.Comments.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت کامنت ها";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کامنت ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name"></label>
                        <input class="form-control" asp-for="SearchModel.Name" placeholder="نام کاربر">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Email"></label>
                        <input class="form-control" asp-for="SearchModel.Email" placeholder="ایمیل کاربر">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کامنت ها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>نام</th>
                                    <th>ایمیل</th>
                                    <th>پیام</th>
                                    <th>تاریخ</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Comments)
                                {
                                    <tr>
                                        <td>@Html.FaNumbersPlainText(@item.Id)</td>
                                        <td>@Html.FaNumbersPlainText(@item.Name)</td>
                                        <td>@Html.FaNumbersPlainText(@item.Email)</td>
                                        <td>@Html.FaNumbersPlainText(@item.Message)</td>
                                        <td>@Html.FaPersianDate(@item.CommentDate)</td>
                                        <td class="text-center">
                                            @if (!item.IsCanceled && !item.IsConfirmed)
                                            {
                                                <span class="text-warning">در انتظار</span>
                                            }
                                            @if (!item.IsCanceled && item.IsConfirmed)
                                            {
                                                <span class="text-success">تایید شده</span>
                                            }
                                            @if (!item.IsConfirmed && item.IsCanceled)
                                            {
                                                <span class="text-danger">کنسل شده</span>
                                            }
                                        </td>
                                        <td>
                                            @if (!item.IsConfirmed && !item.IsCanceled)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Confirm" asp-route-id="@item.Id"
                                                   class="btn btn-success m-1">تأیید</a>
                                                <a asp-page="./Index" asp-page-handler="Cancel" asp-route-id="@item.Id"
                                                   class="btn btn-danger m-1">کنسل</a>
                                            }
                                            @if (item.IsConfirmed && !item.IsCanceled)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Cancel" asp-route-id="@item.Id"
                                                   class="btn btn-danger m-1">کنسل</a>
                                            }
                                            @if (!item.IsConfirmed && item.IsCanceled)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Confirm" asp-route-id="@item.Id"
                                                   class="btn btn-success m-1">تأیید</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}